config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="home")),
    path("equip/", include("equips.urls", namespace="equips")),
    path("user/", include("users.urls", namespace="users")),
    path("reservation/", include("reservations.urls", namespace="reservations")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

equips/urls.py
from django.urls import path
from . import views

app_name = "equips"

urlpatterns = [
    path("list/", views.EquipView.as_view(), name="equiplist"),
    path("list/<int:pk>/", views.EquipDetail.as_view(), name="detail"),
]

reservations/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "reservations"

urlpatterns = [
    path("reservation/", views.MakeReservationView.as_view(), name="makereservation"),
    path(
        "instantreservation/",
        views.InstantReservationView.as_view(),
        name="instantreservation",
    ),
    path("list/", views.ReservationListView.as_view(), name="reservationlist"),
    path(
        "confirmlist/",
        views.ConfirmRevervationListView.as_view(),
        name="confirmreservationlist",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="reservationdetail"),
    path(
        "update-acception/<int:pk>/",
        views.UpdateAcceptView.as_view(),
        name="updateacception",
    ),
    path(
        "update-reservation-from-before-to-now/<int:pk>/",
        views.UpdateReservationNowView.as_view(),
        name="updatereservationnow",
    ),
    path(
        "update-reservation-from-now-to-finish/<int:pk>/",
        views.UpdateReservationFinishView.as_view(),
        name="updatereservationfinish",
    ),
    path(
        "confirm-instant-reservation/<int:pk>/",
        views.InstantReservationConfirmView.as_view(),
        name="confirminstantreservation",
    ),
    path(
        "delete/<int:pk>/",
        views.ReservationDeleteView.as_view(),
        name="reservationdelete",
    ),
    path(
        "reservation-change/<int:pk>/",
        views.ReservationChangeView.as_view(),
        name="reservationchange",
    ),
    path(
        "update-instant-reservation/<int:pk>/",
        views.InstantReservationChangeView.as_view(),
        name="instantreservationchange",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block title_name%}{% endblock title_name%}</title>
</head>

<body>

    {% include "partial/messages.html" %}

    <header
        class="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white inset-0">
        <div class="flex items-center w-full">
            <a class="mr-6" href="{% url "core:core" %}">
                <i class="fas fa-video text-5xl ml-5"></i>
            </a>
        </div>

        {% include "partial/nav.html" %}

    </header>


    {% block content %}
    {% endblock %}

    {% include "partial/footer.html" %}


</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}
SSIZEN.NET EQUIP
{% endblock title_name %}


{% block content %}
<div class="container mt-24 mx-auto lg:w-5/12 md:w-1/2">
        <a href="{% url "reservations:reservationlist" %}" class="homelist_sn bg-orange-400 hover:bg-orange-500"><i
                        class="fas fa-list-ul mr-3"></i>예약목록</a>
        <a href="{% url "reservations:makereservation" %}" class="homelist_sn bg-green-400 hover:bg-green-500"><i
                        class="far fa-clipboard mr-3"></i>장비예약</a>
        <a href="{% url "reservations:instantreservation" %}" class="homelist_sn bg-yellow-500 hover:bg-yellow-600"><i
                        class="fas fa-exchange-alt mr-3"></i>당일대여</a>
        <a href="{% url "reservations:confirmreservationlist" %}" class="homelist_sn bg-blue-400 hover:bg-blue-500"><i
                        class="fas fa-sign-in-alt mr-3"></i>당일승인</a>
        <!-- <a href="{% url "equips:equiplist" %}" class="homelist_sn bg-red-400 hover:bg-red-500"><i
                        class="fas fa-list-ul mr-3"></i>장비목록</a> -->
</div>
{% endblock content %}