config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="home")),
    path("equip/", include("equips.urls", namespace="equips")),
    path("user/", include("users.urls", namespace="users")),
    path("reservation/", include("reservations.urls", namespace="reservations")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="updateprofile"),
    path(
        "update-password/",
        views.UpdatePasswordView.as_view(success_url=reverse_lazy("core:core")),
        name="updatepassword",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from django.db import models
from core import managers as core_managers

# Create your models here.


class User(AbstractUser):

    """ Custom User Model """

    # define departure

    DEPARTURE_DIRECT = "dirc"
    DEPARTURE_WRITE = "writ"
    DEPARTURE_TECH = "tech"
    DEPARTURE_ENTER = "entr"
    DEPARTURE_WEB = "webc"

    DEPARTURE_CHOICES = (
        (DEPARTURE_DIRECT, "연출부"),
        (DEPARTURE_WRITE, "구성작가부"),
        (DEPARTURE_TECH, "방송기술부"),
        (DEPARTURE_ENTER, "엔터테이너부"),
        (DEPARTURE_WEB, "웹컨텐츠부"),
    )

    avatar = models.ImageField(null=True, blank=True, upload_to="avatars")
    departure = models.CharField(choices=DEPARTURE_CHOICES, max_length=6)
    order = models.IntegerField(null=True)
    kakaotalk = models.CharField(max_length=18)
    upperuser = models.BooleanField(default=False)

    objects = core_managers.CustomUserManager()

    def __str__(self):
        return self.username

    def clean_username(self):
        result = self.cleaned_data
        return result

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from . import models


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = (
            "username",
            "password",
            "re_password",
            "email",
            "departure",
            "order",
            "kakaotalk",
        )

        labels = {
            "username": "이름",
            "password": "비밀번호",
            "re_password": "비밀번호 확인",
            "email": "이메일 주소",
            "departure": "부서",
            "order": "기수",
            "kakaotalk": "카카오톡 ID",
        }

        # it depends on User model

    username = forms.CharField(widget=forms.TextInput(), label="이름")
    password = forms.CharField(widget=forms.PasswordInput(), label="비밀번호")
    re_password = forms.CharField(widget=forms.PasswordInput(), label="비밀번호 확인")

    def clean_re_password(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if password != re_password:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            try:
                password_validation.validate_password(password, self.instance)

                return password
            except forms.ValidationError as error:
                self.add_error("password", error)
            return password

    def save(self, *args, **kwargs):
        user = super().save()
        password = self.cleaned_data.get("password")
        user.set_password(password)
        user.save()


class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "이름"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"})
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호 오류!"))
        except models.User.DoesNotExist:
            self.add_error("username", forms.ValidationError("해당 유저가 존재하지 않습니다"))

users/views.py
from django.shortcuts import redirect, reverse, render
from django.contrib.auth import login, logout, authenticate
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib import messages
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:core")

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        username_info = user.clean_username.__self__
        messages.add_message(self.request, messages.INFO, f"{username_info}님 어서오세요!")
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:core")


def logout_view(request):
    messages.info(request, "안녕히가세요!")
    logout(request)
    return redirect(reverse("core:core"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    # success_url = reverse_lazy("core:core")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "회원가입 완료!")
        # Put function here
        return reverse_lazy("core:core")


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "username",
        "avatar",
        "email",
        "departure",
        "order",
        "kakaotalk",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["username"].widget.attrs = {"placeholder": ""}
        form.fields["username"].label = "이름"
        form.fields["username"].help_text = ""
        form.fields["email"].widget.attrs = {"placeholder": ""}
        form.fields["email"].label = "이메일"
        form.fields["departure"].widget.attrs = {"placeholder": ""}
        form.fields["departure"].label = "부서"
        form.fields["order"].widget.attrs = {"placeholder": ""}
        form.fields["order"].label = "기수"
        form.fields["kakaotalk"].widget.attrs = {"placeholder": ""}
        form.fields["kakaotalk"].label = "카카오톡 ID"
        return form

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "수정 완료!")
        return self.request.user.get_absolute_url()


class UpdatePasswordView(mixins.LoggedInOnlyView, PasswordChangeView):

    model = models.User
    template_name = "users/update-password.html"
    fields = (
        "old_password",
        "new_password1",
        "new_password2",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].label = ""
        form.fields["old_password"].widget.attrs = {"placeholder": "기본 비밀번호"}
        form.fields["new_password1"].label = ""
        form.fields["new_password1"].widget.attrs = {"placeholder": "새 비밀번호"}
        form.fields["new_password2"].label = ""
        form.fields["new_password2"].widget.attrs = {"placeholder": "새 비밀번호 확인"}
        return form

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, "수정 완료!")
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends "base.html" %}

{% block title_name %}
Login
{% endblock title_name %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center p-5 border border-gray-500 mt-24">
    <form class="form" method="post" action="{% url "users:login" %}">
        {% csrf_token %}

        {{form.username}}
        <span class="font-bold text-red-600 text-center">{{form.username.errors}}</span>

        {{form.password}}
        <span class="font-bold text-red-600 text-center">{{form.password.errors}}</span>

        <button class="btn_sn mt-10">로그인</button>
    </form>

    <span class="mt-5">아직 계정이 없으시면 <a href="{% url "users:signup" %}" class="font-bold text-lg text-blue-700">이곳</a>을
        누르세요</span>
</div>

{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block title_name %}
Sign Up
{% endblock title_name %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center p-5 border border-gray-500 mt-24">
    <form method="post" action="{% url "users:signup" %}" class="font-bold form">
        {% csrf_token %}


        {{form.username.label}}
        {{form.username}}
        <span class="font-bold text-red-600 text-center">{{form.username.errors}}</span>


        {{form.password.label}}
        {{form.password}}
        <span class="font-bold text-red-600 text-center">{{form.password.errors}}</span>


        {{form.re_password.label}}
        {{form.re_password}}
        <span class="font-bold text-red-600 text-center">{{form.re_password.errors}}</span>


        {{form.email.label}}
        {{form.email}}
        <span class="font-bold text-red-600 text-center">{{form.email.errors}}</span>


        {{form.departure.label}}
        {{form.departure}}
        <span class="font-bold text-red-600 text-center">{{form.departure.errors}}</span>


        {{form.order.label}}
        {{form.order}}
        <span class="font-bold text-red-600 text-center">{{form.order.errors}}</span>


        {{form.kakaotalk.label}}
        {{form.kakaotalk}}
        <span class="font-bold text-red-600 text-center">{{form.kakaotalk.errors}}</span>

        <button class="btn_sn mt-10">회원가입</button>
    </form>
    <span class="mt-5">이미 회원이시라면 <a href="{% url "users:signup" %}"
            class="font-bold text-lg text-blue-700">로그인</a>하세요!</span>
</div>

{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block title_name %}
Change Password
{% endblock title_name %}

{% block content %}


<div class="container lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center p-5 border border-gray-500 mt-24">

    <form class="form text-center" method="post" action="{% url "users:updatepassword" %}"
        enctype="multipart/form-data">
        {% csrf_token %}

        {{form.old_password}}
        <span class="font-bold text-red-600 text-center">{{form.old_password.errors}}</span>

        {{form.new_password1}}
        <span class="font-bold text-red-600 text-center">{{form.new_password1.errors}}</span>

        {{form.new_password2}}
        <span class="font-bold text-red-600 text-center">{{form.new_password2.errors}}</span>

        <button class="btn_sn mt-10">비밀번호 변경</button>
    </form>
</div>


{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block title_name %}
Update Profile
{% endblock title_name %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center p-5 border border-gray-500 mt-24">
    <form class="" method="post" action="{% url "users:updateprofile" %}" enctype="multipart/form-data">
        {% csrf_token %}

        <span class="form font-bold">{{form.username.label}}</span>
        <span class="form">{{form.username}}</span>
        <span class="font-bold text-red-600 text-center">{{form.username.errors}}</span>


        <span class="form">{{form.email.label}}</span>
        <span class="form">{{form.email}}</span>
        <span class="font-bold text-red-600 text-center">{{form.email.errors}}</span>


        <span class="form">{{form.departure.label}}</span>
        <span class="form">{{form.departure}}</span>
        <span class="font-bold text-red-600 text-center">{{form.departure.errors}}</span>


        <span class="form">{{form.order.label}}</span>
        <span class="form">{{form.order}}</span>
        <span class="font-bold text-red-600 text-center">{{form.order.errors}}</span>


        <span class="form">{{form.kakaotalk.label}}</span>
        <span class="form">{{form.kakaotalk}}</span>
        <span class="font-bold text-red-600 text-center">{{form.kakaotalk.errors}}</span>



        <button class="btn_sn mt-10">수정하기</button>
    </form>
</div>

{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block title_name %}
{{user.email}}
{% endblock title_name %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center p-5 border border-gray-500 mt-24">


    <!-- <div class="bg-black rounded-full h-20 w-20 flex justify-center overflow-hidden mb-4">
        {% if user_obj.avatar %}
        <img src="{{user_obj.avatar.url}}" alt="{{user_obj.first_name}} Avatar"></img>
        {% else %}
        <span class="text-5xl text-white text-center pt-1">{{user_obj.username|first}}</span>
        {% endif %}
    </div> -->

    <div class="flex justify-center overflow-hidden mb-4">
        {% if user_obj.avatar %}
        <img src="{{user_obj.avatar.url}}" alt="{{user_obj.name}}" class="w-full h-full"></img>
        {% else %}
        <span class="flex bg-black rounded-full text-center w-64 h-64">
            <span class="flex text-3xl text-white my-auto mx-auto">{{user_obj.username}}</span>
        </span>
        {% endif %}
    </div>


    <span class="text-center font-bold">부서: {{user_obj.departure}}<br></span>
    <span class="text-center font-bold">기수: {{user_obj.order}}<br></span>
    <span class="text-center font-bold">카카오톡 ID: {{user_obj.kakaotalk}}<br></span>

    {% if user_obj.upperuser %}
    <span class="uppercase font-bold border border-black px-1 rounded-lg mt-5 mb-1">부장</span>
    {% else %}
    <span class="uppercase font-bold border border-black px-1 rounded-lg mt-5 my-1">부원</span>
    {% endif %}


    {% if user == user_obj %}
    <a href="{% url "users:updateprofile" %}" class="btn_sn mt-10 mb-2 text-lg">프로필 수정</a>
    <a href="{% url "users:updatepassword" %}" class="btn_sn my-2 text-lg"><span>비밀번호 변경</span></a>
    {% endif %}

</div>

{% endblock %}