config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="home")),
    path("equip/", include("equips.urls", namespace="equips")),
    path("user/", include("users.urls", namespace="users")),
    path("reservation/", include("reservations.urls", namespace="reservations")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views as core_views

app_name = "core"

urlpatterns = [path("", core_views.HomeView.as_view(), name="core")]

equips/urls.py
from django.urls import path
from . import views

app_name = "equips"

urlpatterns = [
    path("list/", views.EquipView.as_view(), name="equiplist"),
    path("list/<int:pk>/", views.EquipDetail.as_view(), name="detail"),
]

reservations/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "reservations"

urlpatterns = [
    path("reservation/", views.MakeReservationView.as_view(), name="makereservation"),
    path(
        "instantreservation/",
        views.InstantReservationView.as_view(),
        name="instantreservation",
    ),
    path("list/", views.ReservationListView.as_view(), name="reservationlist"),
    path(
        "confirmlist/",
        views.ConfirmRevervationListView.as_view(),
        name="confirmreservationlist",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="reservationdetail"),
    path(
        "update-acception/<int:pk>/",
        views.UpdateAcceptView.as_view(),
        name="updateacception",
    ),
    path(
        "update-reservation-from-before-to-now/<int:pk>/",
        views.UpdateReservationNowView.as_view(),
        name="updatereservationnow",
    ),
    path(
        "update-reservation-from-now-to-finish/<int:pk>/",
        views.UpdateReservationFinishView.as_view(),
        name="updatereservationfinish",
    ),
    path(
        "confirm-instant-reservation/<int:pk>/",
        views.InstantReservationConfirmView.as_view(),
        name="confirminstantreservation",
    ),
    path(
        "delete/<int:pk>/",
        views.ReservationDeleteView.as_view(),
        name="reservationdelete",
    ),
    path(
        "reservation-change/<int:pk>/",
        views.ReservationChangeView.as_view(),
        name="reservationchange",
    ),
    path(
        "update-instant-reservation/<int:pk>/",
        views.InstantReservationChangeView.as_view(),
        name="instantreservationchange",
    ),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="updateprofile"),
    path(
        "update-password/",
        views.UpdatePasswordView.as_view(success_url=reverse_lazy("core:core")),
        name="updatepassword",
    ),
]

templates/partial/confirm_reservation_card.html
{% if reservation.instant_boolean %}


<div class="w-full">
    <table class="w-full table-auto text-center">

        <tr class="border-b border-gray-500 
        {% if reservation.lender == user %}bg-yellow-200 rounded-md{% endif %}">
            <td class="h-auto w-1/12 px-2 py-1">{{reservation.lender}}</td>
            <td class="h-auto px-2 w-1/6 py-1">
                <span class="font-bold">
                    [

                    {% if reservation.catagory == reservation.CATAGOTY_INFO %}
                    <span>정보</span>
                    {% elif reservation.catagory == reservation.CATAGOTY_SCHOOL_EVENTS %}
                    <span>교내행사</span>
                    {% elif reservation.catagory == reservation.CATAGORY_REFINE %}
                    <span>교양</span>
                    {% elif reservation.catagory == reservation.CATAGOTY_REALITY %}
                    <span>예능</span>
                    {% elif reservation.catagory == reservation.CATAGORY_PERFORM %}
                    <span>공연</span>
                    {% elif reservation.catagory == reservation.CATAGORY_RADIO %}
                    <span>라디오</span>
                    {% elif reservation.catagory == reservation.CATAGORY_SURV %}
                    <span>영상제</span>
                    {% elif reservation.catagory == reservation.CATAGORY_PERSONAL %}
                    <span>개인</span>
                    {% else %}
                    <span>{{reservation.catagory}}</span>

                    {% endif %}
                    ]
                </span>
                <br>
                {{reservation.purpose}}
            </td>
            <td class="h-auto px-2 w-5/12 py-1">
                {{reservation.get_equipments}}

                {% if reservation.lender == user %}

                <br>
                <a href="{% url "reservations:reservationdelete" reservation.pk %}">
                    <span class="text-sm text-gray-600 font-bold">
                        [취소]
                    </span>
                </a>

                {% endif %}

            </td>
            <td class="h-auto px-2 w-1/4 py-1">{{reservation.check_in}} <br>~<br> {{reservation.check_out}}
            </td>
            <td class="h-auto px-2 w-1/6 py-1">
                {% if reservation.lender == user %}
                <a href="{% url "reservations:confirminstantreservation" reservation.pk %}"
                    class="text-center text-4xl py-2 text-green-500 hover:text-green-700">
                    <i class="fas fa-user-check"></i>
                </a>
                {% else %}
                <span class="text-center text-4xl py-2 text-yellow-500">
                    <i class="fas fa-user-check"></i>
                </span>
                {% endif %}
            </td>

        </tr>

    </table>
</div>


{% endif %}

templates/partial/equip_card.html
<div class="w-1/4 mb-10 px-5">
    <a href="{% url "equips:detail" equip.pk %}">



        {% if equip.photo %}
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{equip.photo.url}});">
        </div>
        {% else %}
        <img src="#" alt="#">
        {% endif %}

        <div class="flex justify-between mb-2">
            <div class="w-70% h-7">
                <span class="text-gray-600 text-sm">{{equip.serial_number}}</span>
                <span class="text-black text-base font-bold">{{equip.name}}</span>
            </div>
            {% if equip.enable %}
            <span class="text-center"><i class="fas fa-check-circle text-green-600 text-2xl"></i></span>
            {% else %}
            <span class="text-center"><i class="fas fa-times-circle text-red-600 text-2xl"></i></span>
            {% endif %}
        </div>



    </a>
</div>

templates/partial/footer.html
<footer class="mx-auto py-6 border-t border-gray-500 mt-10">
    <div class="mx-auto w-1/2">
        <ul class="text-center text-gray-600 text-sm">
            <li class=""><a href="http://ssizen.net/">숭실대학교 인터넷방송국 SSIZEN.NET</a></li>
            <li class="">Adress: 서울특별시 동작구 상도로 369 학생회관 2층 202호</li>
            <li class="">Tel: 02-820-0768</li>
            <li class="">Developer: &copyMin</li>
        </ul>
    </div>
</footer>

templates/partial/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="message_sn font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-3/12 text-center {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partial/nav.html
<ul class="flex items-center text-sm font-bold h-full">



    <li class="nav_link_sn">
        <a href="{% url "reservations:reservationlist" %}" class="mx-auto">예약목록</a>
    </li>
    <li class="nav_link_sn">
        <a href="{% url "reservations:makereservation" %}" class="mx-auto">장비예약</a>
    </li>
    <li class="nav_link_sn">
        <a href="{% url "reservations:instantreservation" %}" class="mx-auto">당일예약</a>
    </li>
    <!-- <li class="nav_link_sn">
        <a href="{% url "equips:equiplist" %}" class="mx-auto">장비목록</a>
    </li> -->


    {% if user.is_authenticated %}
    <li class="nav_link_sn">
        <a href="{{user.get_absolute_url}}" class="mx-auto">내 프로필</a>
    </li>
    <li class="nav_link_sn">
        <a href="{% url "users:logout" %}" class="mx-auto">로그아웃</a></li>
    {% else %}
    <li class="nav_link_sn">
        <a href="{% url "users:signup" %}" class="mx-auto">회원가입</a></li>
    <li class="nav_link_sn">
        <a href="{% url "users:login" %}" class="mx-auto">로그인</a></li>
    {% endif %}

</ul>

templates/partial/reservation_card.html
{% if reservation.instant_boolean == False %}


<div class="w-full">
    <table class="w-full table-auto text-center">

        <tr class="border-b border-gray-500 
        {% if reservation.check_in < after_1h and reservation.check_out > before_1h and reservation.lender == user %} 
        bg-red-200 rounded-md
        {% elif reservation.lender == user %} 
        bg-yellow-200 rounded-md
        {% endif %}">
            <td class=" h-auto w-1/12 px-2 py-1">{{reservation.lender}}</td>
            <td class="h-auto px-2 w-1/6 py-1">
                <span class="font-bold">
                    [

                    {% if reservation.catagory == reservation.CATAGOTY_INFO %}
                    <span>정보</span>
                    {% elif reservation.catagory == reservation.CATAGOTY_SCHOOL_EVENTS %}
                    <span>교내행사</span>
                    {% elif reservation.catagory == reservation.CATAGORY_REFINE %}
                    <span>교양</span>
                    {% elif reservation.catagory == reservation.CATAGOTY_REALITY %}
                    <span>예능</span>
                    {% elif reservation.catagory == reservation.CATAGORY_PERFORM %}
                    <span>공연</span>
                    {% elif reservation.catagory == reservation.CATAGORY_RADIO %}
                    <span>라디오</span>
                    {% elif reservation.catagory == reservation.CATAGORY_SURV %}
                    <span>영상제</span>
                    {% elif reservation.catagory == reservation.CATAGORY_PERSONAL %}
                    <span>개인</span>
                    {% else %}
                    <span>{{reservation.catagory}}</span>

                    {% endif %}
                    ]
                </span>
                <br>
                {{reservation.purpose}}
            </td>
            <td class="h-auto px-2 w-5/12 py-1">
                {{reservation.get_equipments}}


                {% if reservation.lender == user %}

                <br>

                {% if reservation.check_in.day != now_day %}
                <a href="{% url "reservations:reservationchange" reservation.pk %}" class="mx-2">
                    <span class="text-sm text-gray-600 font-bold">
                        [수정]
                    </span>
                </a>
                {% elif reservation.accept and reservation.status != reservation.STATUS_FINISH %}
                <a href="{% url "reservations:instantreservationchange" reservation.pk %}" class="mx-2">
                    <span class="text-sm text-gray-600 font-bold">
                        [연장/추가대여]
                    </span>
                </a>
                {% endif %}

                <a href="{% url "reservations:reservationdelete" reservation.pk %}" class="mx-2">
                    <span class="text-sm text-gray-600 font-bold">
                        [취소]
                    </span>
                </a>

                {% endif %}

            </td>
            <td class="h-auto px-2 w-1/4 py-1">{{reservation.check_in}} <br>~<br> {{reservation.check_out}}
            </td>
            <td class="h-auto px-2 w-1/12 py-1">

                {% if reservation.status == reservation.STATUS_BEFORE %}

                {% if reservation.lender == user and reservation.accept and reservation.check_in < after_1h %}
                <a href="{% url "reservations:updatereservationnow" reservation.pk %}"
                    class="py-6 text-black hover:text-gray-600"><span class="">대여전</span></a>
                {% else %}
                <span>대여전</span>
                {% endif %}

                {% elif reservation.status == reservation.STATUS_NOW %}

                {% if reservation.lender == user and reservation.accept %}
                <a href="{% url "reservations:updatereservationfinish" reservation.pk %}"
                    class="py-6 text-red-600"><span class="font-bold text-red-600 hover:text-red-700">대여중</span></a>
                {% else %}
                <span class="font-bold text-red-600">대여중</span>
                {% endif %}

                {% elif reservation.status == reservation.STATUS_FINISH %}

                <span class="text-green-600">반납</span>

                {% endif %}

            </td>
            <td class="h-auto px-2 w-1/12 py-1">


                {% if user.upperuser %}
                <a href="{% url "reservations:updateacception" reservation.pk %}">
                    {% if reservation.accept %}
                    <span class="text-center"><i
                            class="fas fa-check-circle text-green-600 text-2xl hover:text-green-700"></i></span>
                    {% else %}
                    <span class="text-center"><i
                            class="fas fa-times-circle text-red-600 text-2xl hover:text-red-700"></i></span>
                    {% endif %}
                </a>

                {% else %}

                {% if reservation.accept %}
                <span class="text-center"><i class="fas fa-check-circle text-green-600 text-2xl"></i></span>
                {% else %}
                <span class="text-center"><i class="fas fa-times-circle text-red-600 text-2xl"></i></span>
                {% endif %}

                {% endif %}


            </td>
        </tr>

    </table>
</div>


{% endif %}